In [10]:
import pandas as pd
import os
import funciones as fn

a) Carga de archivos (csv, xlsx, html y json) a dataframes .

In [11]:
df=fn.cargar_dataset("Rio.csv")
df

,Unnamed: 0,source,name,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,0,city scrape,Unbelievable Ocean View Apartment,2011-11-19,"Rio de Janeiro, Brazil",a few days or more,0%,0%,f,Vidigal,...,4.33,4.67,4.33,4.00,f,1,1,0,0,0.05
1,1,city scrape,EXCELENTE APARTAMENTO EM COPACABANA,2013-07-15,"Rio de Janeiro, Brazil",NaN,NaN,NaN,f,NaN,...,4.97,4.97,4.97,4.86,t,2,2,0,0,2.31
2,2,city scrape,Comfort em Copacabana,2011-11-20,"Rio de Janeiro, Brazil",within an hour,100%,100%,t,Copacabana,...,4.94,5.00,4.97,4.94,t,5,3,2,0,0.25
3,3,city scrape,Amazing Huge Apartment in Leblon,2011-04-25,"Rio de Janeiro, Brazil",NaN,NaN,NaN,f,Leblon,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
4,4,city scrape,Lindo quarto sossegado para temporada,2011-05-04,"Rio de Janeiro, Brazil",within a few hours,100%,20%,f,Santa Teresa,...,5.00,5.00,4.60,4.80,f,5,0,5,0,0.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39494,39494,city scrape,Copa Reformado 1 qrt perto do metrô,2014-06-27,"Rio de Janeiro, Brazil",within an hour,100%,99%,NaN,Copacabana,...,NaN,NaN,NaN,NaN,f,20,20,0,0,NaN
39495,39495,city scrape,Casa Sabiá,2022-08-24,NaN,NaN,NaN,NaN,f,Cachambi,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
39496,39496,city scrape,Apartamento na Barata Ribeiro - Copacabana,2020-03-07,"State of Rio de Janeiro, Brazil",within an hour,100%,100%,f,Copacabana,...,NaN,NaN,NaN,NaN,t,1,1,0,0,NaN
39497,39497,city scrape,No coração de Ipanema…,2016-04-14,"State of Rio de Janeiro, Brazil",within an hour,100%,100%,f,Ipanema,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
39498,39498,city scrape,Aconchego de Copanema!,2016-03-08,"Rio de Janeiro, Brazil",NaN,NaN,NaN,f,Copacabana,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN

b) Sustitución de valores nulos con el método de “ffill”.

In [12]:
df_b=fn.sustitución_ffill(df)
df_b

/Users/josemorales/Desktop/Concentracion Freddy/Actividades/funciones.py:39: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  cualitativas = cualitativas_con_nulos.fillna(method="ffill")

,Unnamed: 0,host_listings_count,host_total_listings_count,accommodates,bathrooms,bedrooms,beds,minimum_nights,maximum_nights,minimum_minimum_nights,...,host_identity_verified,neighbourhood,neighbourhood_cleansed,property_type,room_type,price,has_availability,first_review,last_review,instant_bookable
0,0,1.0,3.0,4,1.0,2.0,2.0,1,90,1,...,t,"Rio de Janeiro, Brazil",Vidigal,Entire rental unit,Entire home/apt,$236.00,t,2013-02-16,2019-10-05,f
1,1,3.0,3.0,4,1.0,1.0,1.0,3,29,1,...,f,"Rio de Janeiro, Brazil",Copacabana,Entire rental unit,Entire home/apt,$723.00,t,2011-12-06,2024-12-14,t
2,2,6.0,6.0,2,1.0,1.0,2.0,2,30,2,...,t,"Rio de Janeiro, Brazil",Copacabana,Private room in rental unit,Private room,"$1,146.00",t,2014-07-01,2024-05-06,t
3,3,1.0,2.0,6,3.5,3.0,3.0,2,7,2,...,f,"Rio de Janeiro, Brazil",Leblon,Entire rental unit,Entire home/apt,"$6,742.00",t,2014-07-01,2024-05-06,f
4,4,5.0,6.0,1,1.0,1.0,1.0,60,200,60,...,t,"Rio de Janeiro, Brazil",Santa Teresa,Private room in home,Private room,$61.00,t,2015-03-11,2024-06-22,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39494,39494,25.0,27.0,4,2.0,1.0,2.0,1,90,1,...,t,"Rio de Janeiro, Brazil",Copacabana,Entire rental unit,Entire home/apt,$957.00,t,2024-12-26,2024-12-27,f
39495,39495,1.0,1.0,8,1.0,1.0,1.0,1,365,1,...,t,"Rio de Janeiro, Brazil",Jacarezinho,Entire home,Entire home/apt,$288.00,t,2024-12-26,2024-12-27,f
39496,39496,1.0,1.0,6,1.0,1.0,4.0,2,365,2,...,t,"Rio de Janeiro, Brazil",Copacabana,Entire rental unit,Entire home/apt,$672.00,t,2024-12-26,2024-12-27,t
39497,39497,1.0,1.0,6,1.5,2.0,1.0,2,15,2,...,t,"Rio de Janeiro, Brazil",Ipanema,Entire rental unit,Entire home/apt,"$1,083.00",t,2024-12-26,2024-12-27,f
39498,39498,1.0,1.0,4,1.0,1.0,2.0,3,14,3,...,f,"Rio de Janeiro, Brazil",Copacabana,Entire rental unit,Entire home/apt,"$1,296.00",t,2024-12-26,2024-12-27,f

c) Sustitución de valores nulos con el método de “bfill”.

In [13]:
df_c=fn.sustitución_bfill(df)
df_c

/Users/josemorales/Desktop/Concentracion Freddy/Actividades/funciones.py:56: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  cualitativas = cualitativas_con_nulos.fillna(method="bfill")

,Unnamed: 0,host_listings_count,host_total_listings_count,accommodates,bathrooms,bedrooms,beds,minimum_nights,maximum_nights,minimum_minimum_nights,...,host_identity_verified,neighbourhood,neighbourhood_cleansed,property_type,room_type,price,has_availability,first_review,last_review,instant_bookable
0,0,1.0,3.0,4,1.0,2.0,2.0,1,90,1,...,t,"Rio de Janeiro, Brazil",Vidigal,Entire rental unit,Entire home/apt,$236.00,t,2013-02-16,2019-10-05,f
1,1,3.0,3.0,4,1.0,1.0,1.0,3,29,1,...,f,"Rio de Janeiro, Brazil",Copacabana,Entire rental unit,Entire home/apt,$723.00,t,2011-12-06,2024-12-14,t
2,2,6.0,6.0,2,1.0,1.0,2.0,2,30,2,...,t,"Rio de Janeiro, Brazil",Copacabana,Private room in rental unit,Private room,"$1,146.00",t,2014-07-01,2024-05-06,t
3,3,1.0,2.0,6,3.5,3.0,3.0,2,7,2,...,f,"Rio de Janeiro, Brazil",Leblon,Entire rental unit,Entire home/apt,"$6,742.00",t,2015-03-11,2024-06-22,f
4,4,5.0,6.0,1,1.0,1.0,1.0,60,200,60,...,t,"Rio de Janeiro, Brazil",Santa Teresa,Private room in home,Private room,$61.00,t,2015-03-11,2024-06-22,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39494,39494,25.0,27.0,4,2.0,1.0,2.0,1,90,1,...,t,"Rio de Janeiro, Brazil",Copacabana,Entire rental unit,Entire home/apt,$957.00,t,NaN,NaN,f
39495,39495,1.0,1.0,8,1.0,1.0,1.0,1,365,1,...,t,"Rio de Janeiro, Brazil",Jacarezinho,Entire home,Entire home/apt,$288.00,t,NaN,NaN,f
39496,39496,1.0,1.0,6,1.0,1.0,4.0,2,365,2,...,t,"Rio de Janeiro, Brazil",Copacabana,Entire rental unit,Entire home/apt,$672.00,t,NaN,NaN,t
39497,39497,1.0,1.0,6,1.5,2.0,1.0,2,15,2,...,t,NaN,Ipanema,Entire rental unit,Entire home/apt,"$1,083.00",t,NaN,NaN,f
39498,39498,1.0,1.0,4,1.0,1.0,2.0,3,14,3,...,f,NaN,Copacabana,Entire rental unit,Entire home/apt,"$1,296.00",t,NaN,NaN,f

d) Sustitución de valores nulos con el método por un “string concreto”

In [14]:
df_d=fn.sustitución_string(df)
df_d

,Unnamed: 0,host_listings_count,host_total_listings_count,accommodates,bathrooms,bedrooms,beds,minimum_nights,maximum_nights,minimum_minimum_nights,...,host_identity_verified,neighbourhood,neighbourhood_cleansed,property_type,room_type,price,has_availability,first_review,last_review,instant_bookable
0,0,1.0,3.0,4,1.0,2.0,2.0,1,90,1,...,t,"Rio de Janeiro, Brazil",Vidigal,Entire rental unit,Entire home/apt,$236.00,t,2013-02-16,2019-10-05,f
1,1,3.0,3.0,4,1.0,1.0,1.0,3,29,1,...,f,"Rio de Janeiro, Brazil",Copacabana,Entire rental unit,Entire home/apt,$723.00,t,2011-12-06,2024-12-14,t
2,2,6.0,6.0,2,1.0,1.0,2.0,2,30,2,...,t,Sin registro,Copacabana,Private room in rental unit,Private room,"$1,146.00",t,2014-07-01,2024-05-06,t
3,3,1.0,2.0,6,3.5,3.0,3.0,2,7,2,...,f,Sin registro,Leblon,Entire rental unit,Entire home/apt,"$6,742.00",t,Sin registro,Sin registro,f
4,4,5.0,6.0,1,1.0,1.0,1.0,60,200,60,...,t,"Rio de Janeiro, Brazil",Santa Teresa,Private room in home,Private room,$61.00,t,2015-03-11,2024-06-22,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39494,39494,25.0,27.0,4,2.0,1.0,2.0,1,90,1,...,t,Sin registro,Copacabana,Entire rental unit,Entire home/apt,$957.00,t,Sin registro,Sin registro,f
39495,39495,1.0,1.0,8,1.0,1.0,1.0,1,365,1,...,t,Sin registro,Jacarezinho,Entire home,Entire home/apt,$288.00,t,Sin registro,Sin registro,f
39496,39496,1.0,1.0,6,1.0,1.0,4.0,2,365,2,...,t,"Rio de Janeiro, Brazil",Copacabana,Entire rental unit,Entire home/apt,$672.00,t,Sin registro,Sin registro,t
39497,39497,1.0,1.0,6,1.5,2.0,1.0,2,15,2,...,t,Sin registro,Ipanema,Entire rental unit,Entire home/apt,"$1,083.00",t,Sin registro,Sin registro,f
39498,39498,1.0,1.0,4,1.0,1.0,2.0,3,14,3,...,f,Sin registro,Copacabana,Entire rental unit,Entire home/apt,"$1,296.00",t,Sin registro,Sin registro,f

e) Sustitución de valores nulos con el método de “promedio”.

In [15]:
df_e=fn.sustitución_promedio(df)
df_e

,Unnamed: 0,host_listings_count,host_total_listings_count,accommodates,bathrooms,bedrooms,beds,minimum_nights,maximum_nights,minimum_minimum_nights,...,host_identity_verified,neighbourhood,neighbourhood_cleansed,property_type,room_type,price,has_availability,first_review,last_review,instant_bookable
0,0,1.0,3.0,4,1.0,2.0,2.0,1,90,1,...,t,"Rio de Janeiro, Brazil",Vidigal,Entire rental unit,Entire home/apt,$236.00,t,2013-02-16,2019-10-05,f
1,1,3.0,3.0,4,1.0,1.0,1.0,3,29,1,...,f,"Rio de Janeiro, Brazil",Copacabana,Entire rental unit,Entire home/apt,$723.00,t,2011-12-06,2024-12-14,t
2,2,6.0,6.0,2,1.0,1.0,2.0,2,30,2,...,t,NaN,Copacabana,Private room in rental unit,Private room,"$1,146.00",t,2014-07-01,2024-05-06,t
3,3,1.0,2.0,6,3.5,3.0,3.0,2,7,2,...,f,NaN,Leblon,Entire rental unit,Entire home/apt,"$6,742.00",t,NaN,NaN,f
4,4,5.0,6.0,1,1.0,1.0,1.0,60,200,60,...,t,"Rio de Janeiro, Brazil",Santa Teresa,Private room in home,Private room,$61.00,t,2015-03-11,2024-06-22,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39494,39494,25.0,27.0,4,2.0,1.0,2.0,1,90,1,...,t,NaN,Copacabana,Entire rental unit,Entire home/apt,$957.00,t,NaN,NaN,f
39495,39495,1.0,1.0,8,1.0,1.0,1.0,1,365,1,...,t,NaN,Jacarezinho,Entire home,Entire home/apt,$288.00,t,NaN,NaN,f
39496,39496,1.0,1.0,6,1.0,1.0,4.0,2,365,2,...,t,"Rio de Janeiro, Brazil",Copacabana,Entire rental unit,Entire home/apt,$672.00,t,NaN,NaN,t
39497,39497,1.0,1.0,6,1.5,2.0,1.0,2,15,2,...,t,NaN,Ipanema,Entire rental unit,Entire home/apt,"$1,083.00",t,NaN,NaN,f
39498,39498,1.0,1.0,4,1.0,1.0,2.0,3,14,3,...,f,NaN,Copacabana,Entire rental unit,Entire home/apt,"$1,296.00",t,NaN,NaN,f

f) Sustitución de valores nulos con el método de “mediana”.

In [16]:
df_f=fn.sustitución_mediana(df)
df_f

,Unnamed: 0,host_listings_count,host_total_listings_count,accommodates,bathrooms,bedrooms,beds,minimum_nights,maximum_nights,minimum_minimum_nights,...,host_identity_verified,neighbourhood,neighbourhood_cleansed,property_type,room_type,price,has_availability,first_review,last_review,instant_bookable
0,0,1.0,3.0,4,1.0,2.0,2.0,1,90,1,...,t,"Rio de Janeiro, Brazil",Vidigal,Entire rental unit,Entire home/apt,$236.00,t,2013-02-16,2019-10-05,f
1,1,3.0,3.0,4,1.0,1.0,1.0,3,29,1,...,f,"Rio de Janeiro, Brazil",Copacabana,Entire rental unit,Entire home/apt,$723.00,t,2011-12-06,2024-12-14,t
2,2,6.0,6.0,2,1.0,1.0,2.0,2,30,2,...,t,NaN,Copacabana,Private room in rental unit,Private room,"$1,146.00",t,2014-07-01,2024-05-06,t
3,3,1.0,2.0,6,3.5,3.0,3.0,2,7,2,...,f,NaN,Leblon,Entire rental unit,Entire home/apt,"$6,742.00",t,NaN,NaN,f
4,4,5.0,6.0,1,1.0,1.0,1.0,60,200,60,...,t,"Rio de Janeiro, Brazil",Santa Teresa,Private room in home,Private room,$61.00,t,2015-03-11,2024-06-22,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39494,39494,25.0,27.0,4,2.0,1.0,2.0,1,90,1,...,t,NaN,Copacabana,Entire rental unit,Entire home/apt,$957.00,t,NaN,NaN,f
39495,39495,1.0,1.0,8,1.0,1.0,1.0,1,365,1,...,t,NaN,Jacarezinho,Entire home,Entire home/apt,$288.00,t,NaN,NaN,f
39496,39496,1.0,1.0,6,1.0,1.0,4.0,2,365,2,...,t,"Rio de Janeiro, Brazil",Copacabana,Entire rental unit,Entire home/apt,$672.00,t,NaN,NaN,t
39497,39497,1.0,1.0,6,1.5,2.0,1.0,2,15,2,...,t,NaN,Ipanema,Entire rental unit,Entire home/apt,"$1,083.00",t,NaN,NaN,f
39498,39498,1.0,1.0,4,1.0,1.0,2.0,3,14,3,...,f,NaN,Copacabana,Entire rental unit,Entire home/apt,"$1,296.00",t,NaN,NaN,f

g) Sustitución de valores nulos con el método de “constante”.

In [17]:
df_g=fn.sustitución_constante(df)
df_g

,Unnamed: 0,host_listings_count,host_total_listings_count,accommodates,bathrooms,bedrooms,beds,minimum_nights,maximum_nights,minimum_minimum_nights,...,host_identity_verified,neighbourhood,neighbourhood_cleansed,property_type,room_type,price,has_availability,first_review,last_review,instant_bookable
0,0,1.0,3.0,4,1.0,2.0,2.0,1,90,1,...,t,"Rio de Janeiro, Brazil",Vidigal,Entire rental unit,Entire home/apt,$236.00,t,2013-02-16,2019-10-05,f
1,1,3.0,3.0,4,1.0,1.0,1.0,3,29,1,...,f,"Rio de Janeiro, Brazil",Copacabana,Entire rental unit,Entire home/apt,$723.00,t,2011-12-06,2024-12-14,t
2,2,6.0,6.0,2,1.0,1.0,2.0,2,30,2,...,t,NaN,Copacabana,Private room in rental unit,Private room,"$1,146.00",t,2014-07-01,2024-05-06,t
3,3,1.0,2.0,6,3.5,3.0,3.0,2,7,2,...,f,NaN,Leblon,Entire rental unit,Entire home/apt,"$6,742.00",t,NaN,NaN,f
4,4,5.0,6.0,1,1.0,1.0,1.0,60,200,60,...,t,"Rio de Janeiro, Brazil",Santa Teresa,Private room in home,Private room,$61.00,t,2015-03-11,2024-06-22,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39494,39494,25.0,27.0,4,2.0,1.0,2.0,1,90,1,...,t,NaN,Copacabana,Entire rental unit,Entire home/apt,$957.00,t,NaN,NaN,f
39495,39495,1.0,1.0,8,1.0,1.0,1.0,1,365,1,...,t,NaN,Jacarezinho,Entire home,Entire home/apt,$288.00,t,NaN,NaN,f
39496,39496,1.0,1.0,6,1.0,1.0,4.0,2,365,2,...,t,"Rio de Janeiro, Brazil",Copacabana,Entire rental unit,Entire home/apt,$672.00,t,NaN,NaN,t
39497,39497,1.0,1.0,6,1.5,2.0,1.0,2,15,2,...,t,NaN,Ipanema,Entire rental unit,Entire home/apt,"$1,083.00",t,NaN,NaN,f
39498,39498,1.0,1.0,4,1.0,1.0,2.0,3,14,3,...,f,NaN,Copacabana,Entire rental unit,Entire home/apt,"$1,296.00",t,NaN,NaN,f

i) Identificación de valores nulos por columna y por dataframe”.

In [18]:
fn.cuenta_valores_nulos(df)

('Valores nulos por columna:',
 Unnamed: 0                                          0
 source                                              0
 name                                                0
 host_since                                          2
 host_location                                    7646
 host_response_time                               3921
 host_response_rate                               3921
 host_acceptance_rate                             3534
 host_is_superhost                                1170
 host_neighbourhood                               5535
 host_listings_count                                 2
 host_total_listings_count                           2
 host_identity_verified                              2
 neighbourhood                                   22619
 neighbourhood_cleansed                              0
 property_type                                       0
 room_type                                           0
 accommodates                                        0
 bathrooms                                        2890
 bedrooms                                          523
 beds                                             2869
 price                                            2855
 minimum_nights                                      0
 maximum_nights                                      0
 minimum_minimum_nights                              0
 maximum_minimum_nights                              0
 minimum_maximum_nights                              0
 maximum_maximum_nights                              0
 has_availability                                  497
 availability_30                                     0
 availability_60                                     0
 availability_90                                     0
 availability_365                                    0
 number_of_reviews                                   0
 number_of_reviews_ltm                               0
 number_of_reviews_l30d                              0
 first_review                                    10419
 last_review                                     10419
 review_scores_rating                            10419
 review_scores_accuracy                          10420
 review_scores_cleanliness                       10419
 review_scores_checkin                           10420
 review_scores_communication                     10420
 review_scores_location                          10421
 review_scores_value                             10420
 instant_bookable                                    0
 calculated_host_listings_count                      0
 calculated_host_listings_count_entire_homes         0
 calculated_host_listings_count_private_rooms        0
 calculated_host_listings_count_shared_rooms         0
 reviews_per_month                               10419
 dtype: int64,
 'Valores nulos por dataframe: ',
 162184)